# 논문 재현형 엄격 베이스라인

이 노트북은 논문 **"A Case Study on the Data Mining-Based Prediction of Students' Performance for Effective and Sustainable E-Learning"**의 예측 변수 구성을 OULAD 코호트 파일에 맞춰 엄격하게 단순화한 베이스라인 실험이다.

이 실험은 최종 모델링이 아니라, 논문 재현 관점의 기준 성능을 확인하기 위한 베이스라인이다. 따라서 학습 과정과 직접 관련된 두 가지 특징만 사용한다.

- `active_days_until_cutoff`: OULAD에는 직접적인 로그인 수가 없으므로, 컷오프 시점까지 활동한 날짜 수를 access/login proxy로 사용한다.
- `total_click_until_cutoff_*_strategy`: 컷오프 시점까지의 클릭 수를 click count 특징으로 사용한다.

인구통계 특징, 평가/assessment 특징, module/presentation 식별자, activity_type별 클릭 특징, `id_student`, `final_result`, target 컬럼은 엄격 재현 베이스라인의 입력 특징에서 의도적으로 제외한다.

## 1. 실행 환경과 공통 설정

프로젝트 루트에서 실행되는 것을 전제로 경로를 설정한다. 필요한 폴더가 없으면 생성하되, 원본 데이터 파일은 수정하지 않는다.

In [1]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore", category=UserWarning)

def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "data" / "processed").exists() and (candidate / "reports").exists():
            return candidate
    raise FileNotFoundError("Could not find project root containing data/processed and reports")


PROJECT_ROOT = find_project_root(Path.cwd())
DATA_DIR = PROJECT_ROOT / "data" / "processed"
REPORT_TABLE_DIR = PROJECT_ROOT / "reports" / "tables"
REPORT_TABLE_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42

print(f"Project root: {PROJECT_ROOT}")
print(f"Processed data dir exists: {DATA_DIR.exists()}")
print(f"Report table dir: {REPORT_TABLE_DIR}")

Project root: C:\Users\osca0\Dev\studyDataMining\teamproject
Processed data dir exists: True
Report table dir: C:\Users\osca0\Dev\studyDataMining\teamproject\reports\tables

## 2. 실험 대상 파일과 특징 정의

week 5, week 7, week 10 코호트 파일을 사용한다. VLE 중복 처리 방식의 영향을 비교하기 위해 max strategy와 sum strategy를 각각 평가한다.

엄격 재현 베이스라인의 입력 특징은 각 전략별로 정확히 두 개다. `code_module`, `code_presentation`, `id_student`, `final_result`, target 컬럼은 입력 행렬 `X`에 넣지 않는다.

In [2]:
cutoff_files = {
    "week5": DATA_DIR / "features_week5_cohort.csv",
    "week7": DATA_DIR / "features_week7_cohort.csv",
    "week10": DATA_DIR / "features_week10_cohort.csv",
}

feature_sets = {
    "max": [
        "total_click_until_cutoff_max_strategy",
        "active_days_until_cutoff",
    ],
    "sum": [
        "total_click_until_cutoff_sum_strategy",
        "active_days_until_cutoff",
    ],
}

target_name = "target_struggling"

for cutoff, path in cutoff_files.items():
    print(f"{cutoff}: {path} | exists={path.exists()}")

week5: C:\Users\osca0\Dev\studyDataMining\teamproject\data\processed\features_week5_cohort.csv | exists=True
week7: C:\Users\osca0\Dev\studyDataMining\teamproject\data\processed\features_week7_cohort.csv | exists=True
week10: C:\Users\osca0\Dev\studyDataMining\teamproject\data\processed\features_week10_cohort.csv | exists=True

## 3. 타깃 생성과 입력 검증 함수

주요 타깃은 학업 실패/성공 프레이밍에 맞춰 `target_struggling`으로 정의한다.

- `Withdrawn`, `Fail` -> 1, struggling 양성 클래스
- `Pass`, `Distinction` -> 0, non-struggling 음성 클래스

행을 조용히 제거하지 않기 위해, 필요한 컬럼 누락, 알 수 없는 `final_result`, 결측값, 무한값이 있으면 즉시 오류를 발생시킨다.

In [3]:
target_map = {
    "Withdrawn": 1,
    "Fail": 1,
    "Pass": 0,
    "Distinction": 0,
}


def load_and_validate_cohort(path: Path, cutoff: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing cohort file for {cutoff}: {path}")

    df = pd.read_csv(path)
    required_columns = {"final_result", "active_days_until_cutoff"}
    for columns in feature_sets.values():
        required_columns.update(columns)

    missing_columns = sorted(required_columns - set(df.columns))
    if missing_columns:
        raise ValueError(f"{cutoff} is missing required columns: {missing_columns}")

    unknown_results = sorted(set(df["final_result"].dropna().unique()) - set(target_map.keys()))
    if unknown_results:
        raise ValueError(f"{cutoff} has unexpected final_result values: {unknown_results}")

    if df["final_result"].isna().any():
        raise ValueError(f"{cutoff} has missing final_result values")

    df = df.copy()
    df[target_name] = df["final_result"].map(target_map).astype(int)

    print(f"\n[{cutoff}] rows: {len(df):,}")
    print("final_result distribution:")
    print(df["final_result"].value_counts().sort_index())
    print("target_struggling distribution:")
    print(df[target_name].value_counts().sort_index())

    return df


def build_xy(df: pd.DataFrame, features: list[str], cutoff: str, strategy: str):
    missing_values = df[features].isna().sum()
    if missing_values.any():
        raise ValueError(
            f"{cutoff}/{strategy} has missing feature values: "
            f"{missing_values[missing_values > 0].to_dict()}"
        )

    X = df.loc[:, features].copy()
    y = df[target_name].copy()

    if not np.isfinite(X.to_numpy(dtype=float)).all():
        raise ValueError(f"{cutoff}/{strategy} has non-finite feature values")

    return X, y

## 4. 모델과 교차검증 설정

논문 재현형 기준 성능 비교를 위해 Decision Tree, Gaussian Naive Bayes, Random Forest, SVC, KNN을 동일한 5-fold StratifiedKFold로 평가한다.

양성 클래스는 struggling, 즉 `target_struggling = 1`이다. precision, recall, f1은 모두 struggling 클래스를 기준으로 계산한다.

In [4]:
models = {
    "DecisionTreeClassifier": DecisionTreeClassifier(random_state=RANDOM_STATE),
    "GaussianNB": GaussianNB(),
    "RandomForestClassifier": RandomForestClassifier(
        n_estimators=200,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        class_weight=None,
    ),
    "SVC": Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("model", SVC(kernel="rbf", random_state=RANDOM_STATE)),
        ]
    ),
    "KNeighborsClassifier": Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("model", KNeighborsClassifier()),
        ]
    ),
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

scoring = {
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc",
    "accuracy": "accuracy",
}

print("Models:", list(models.keys()))
print("Scoring:", list(scoring.keys()))

Models: ['DecisionTreeClassifier', 'GaussianNB', 'RandomForestClassifier', 'SVC', 'KNeighborsClassifier']
Scoring: ['precision', 'recall', 'f1', 'roc_auc', 'accuracy']

## 5. 컷오프와 VLE 중복 전략별 평가

각 cutoff와 VLE 중복 처리 전략별로 정확히 두 개의 특징만 사용한다. 이 단계는 additional feature engineering을 하지 않으며, 이미 생성된 코호트 파일의 두 learning-process feature만 입력으로 사용한다.

In [7]:
rows = []

for cutoff, path in cutoff_files.items():
    df = load_and_validate_cohort(path, cutoff)

    for strategy, features in feature_sets.items():
        X, y = build_xy(df, features, cutoff, strategy)
        print(f"\nEvaluating {cutoff}/{strategy} with features: {features}")

        for model_name, model in models.items():
            scores = cross_validate(
                clone(model),
                X,
                y,
                cv=cv,
                scoring=scoring,
                n_jobs=-1,
                return_train_score=False,
            )

            result = {
                "cutoff": cutoff,
                "strategy": strategy,
                "model": model_name,
                "n_rows": len(df),
                "positive_class": "struggling",
                "features": ",".join(features),
            }

            for metric in scoring:
                values = scores[f"test_{metric}"]
                result[f"{metric}_mean"] = values.mean()
                result[f"{metric}_std"] = values.std(ddof=1)

            rows.append(result)
            print(
                f"  {model_name}: "
                f"f1={result['f1_mean']:.4f}, "
                f"recall={result['recall_mean']:.4f}, "
                f"roc_auc={result['roc_auc_mean']:.4f}, "
                f"accuracy={result['accuracy_mean']:.4f}"
            )

results = pd.DataFrame(rows)
results

[week5] rows: 27,244

final_result distribution:
final_result
Distinction     3024
Fail            7044
Pass           12361
Withdrawn       4815
Name: count, dtype: int64
target_struggling distribution:
target_struggling
0    15385
1    11859
Name: count, dtype: int64

Evaluating week5/max with features: ['total_click_until_cutoff_max_strategy', 'active_days_until_cutoff']

  DecisionTreeClassifier: f1=0.4884, recall=0.4718, roc_auc=0.5684, accuracy=0.5698

  GaussianNB: f1=0.6209, recall=0.7633, roc_auc=0.6730, accuracy=0.5942

  RandomForestClassifier: f1=0.5166, recall=0.5250, roc_auc=0.5957, accuracy=0.5723

  SVC: f1=0.5249, recall=0.4641, roc_auc=0.6589, accuracy=0.6343

  KNeighborsClassifier: f1=0.5002, recall=0.4752, roc_auc=0.6060, accuracy=0.5867

Evaluating week5/sum with features: ['total_click_until_cutoff_sum_strategy', 'active_days_until_cutoff']

  DecisionTreeClassifier: f1=0.4844, recall=0.4677, roc_auc=0.5640, accuracy=0.5666
  GaussianNB: f1=0.6223, recall=0.7713, roc_auc=0.6735, accuracy=0.5925

  RandomForestClassifier: f1=0.5179, recall=0.5265, roc_auc=0.5917, accuracy=0.5732

  SVC: f1=0.5281, recall=0.4688, roc_auc=0.6588, accuracy=0.6354
  KNeighborsClassifier: f1=0.5059, recall=0.4828, roc_auc=0.6061, accuracy=0.5895

[week7] rows: 26,776
final_result distribution:
final_result
Distinction     3024
Fail            7044
Pass           12361
Withdrawn       4347
Name: count, dtype: int64
target_struggling distribution:
target_struggling
0    15385
1    11391
Name: count, dtype: int64

Evaluating week7/max with features: ['total_click_until_cutoff_max_strategy', 'active_days_until_cutoff']
  DecisionTreeClassifier: f1=0.4872, recall=0.4690, roc_auc=0.5722, accuracy=0.5799
  GaussianNB: f1=0.6210, recall=0.7649, roc_auc=0.6878, accuracy=0.6028

  RandomForestClassifier: f1=0.5154, recall=0.5163, roc_auc=0.6084, accuracy=0.5870

  SVC: f1=0.5203, recall=0.4482, roc_auc=0.6705, accuracy=0.6484
  KNeighborsClassifier: f1=0.5075, recall=0.4835, roc_auc=0.6182, accuracy=0.6008

Evaluating week7/sum with features: ['total_click_until_cutoff_sum_strategy', 'active_days_until_cutoff']

  DecisionTreeClassifier: f1=0.4866, recall=0.4708, roc_auc=0.5690, accuracy=0.5773
  GaussianNB: f1=0.6223, recall=0.7713, roc_auc=0.6884, accuracy=0.6017

  RandomForestClassifier: f1=0.5079, recall=0.5112, roc_auc=0.6035, accuracy=0.5786

  SVC: f1=0.5210, recall=0.4493, roc_auc=0.6707, accuracy=0.6486

  KNeighborsClassifier: f1=0.5093, recall=0.4830, roc_auc=0.6220, accuracy=0.6041

[week10] rows: 26,069
final_result distribution:
final_result
Distinction     3024
Fail            7044
Pass           12361
Withdrawn       3640
Name: count, dtype: int64
target_struggling distribution:
target_struggling
0    15385
1    10684
Name: count, dtype: int64

Evaluating week10/max with features: ['total_click_until_cutoff_max_strategy', 'active_days_until_cutoff']

  DecisionTreeClassifier: f1=0.4864, recall=0.4701, roc_auc=0.5812, accuracy=0.5931
  GaussianNB: f1=0.6180, recall=0.7664, roc_auc=0.7043, accuracy=0.6117

  RandomForestClassifier: f1=0.5080, recall=0.5056, roc_auc=0.6218, accuracy=0.5987

  SVC: f1=0.5159, recall=0.4333, roc_auc=0.6823, accuracy=0.6667
  KNeighborsClassifier: f1=0.5115, recall=0.4816, roc_auc=0.6397, accuracy=0.6230

Evaluating week10/sum with features: ['total_click_until_cutoff_sum_strategy', 'active_days_until_cutoff']
  DecisionTreeClassifier: f1=0.4826, recall=0.4656, roc_auc=0.5767, accuracy=0.5909

  GaussianNB: f1=0.6189, recall=0.7716, roc_auc=0.7050, accuracy=0.6106

  RandomForestClassifier: f1=0.5096, recall=0.5053, roc_auc=0.6227, accuracy=0.6014

  SVC: f1=0.5163, recall=0.4350, roc_auc=0.6818, accuracy=0.6658
  KNeighborsClassifier: f1=0.5075, recall=0.4758, roc_auc=0.6377, accuracy=0.6216

,cutoff,strategy,model,n_rows,positive_class,features,precision_mean,precision_std,recall_mean,recall_std,f1_mean,f1_std,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,week5,max,DecisionTreeClassifier,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.506331,0.005455,0.471794,0.009029,0.488409,0.005643,0.568405,0.005441,0.569814,0.004464
1,week5,max,GaussianNB,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.523263,0.004299,0.763301,0.005482,0.620877,0.003672,0.672957,0.003109,0.594223,0.005226
2,week5,max,RandomForestClassifier,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.508454,0.005570,0.525002,0.003861,0.516581,0.003741,0.595677,0.006471,0.572273,0.005008
3,week5,max,SVC,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.604104,0.005402,0.464120,0.009698,0.524876,0.005905,0.658852,0.003176,0.634305,0.002962
4,week5,max,KNeighborsClassifier,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.528010,0.010540,0.475166,0.010483,0.500191,0.010403,0.606032,0.007638,0.586661,0.008317
5,week5,sum,DecisionTreeClassifier,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.502443,0.008023,0.467663,0.008370,0.484381,0.006201,0.564044,0.008037,0.566620,0.006482
6,week5,sum,GaussianNB,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.521574,0.004439,0.771312,0.006357,0.622311,0.004280,0.673505,0.003113,0.592461,0.005516
7,week5,sum,RandomForestClassifier,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.509510,0.006247,0.526520,0.004350,0.517860,0.004480,0.591672,0.005116,0.573227,0.005525
8,week5,sum,SVC,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.604740,0.004937,0.468842,0.009892,0.528124,0.005821,0.658785,0.002916,0.635369,0.002643
9,week5,sum,KNeighborsClassifier,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.531268,0.003876,0.482840,0.006847,0.505882,0.004856,0.606051,0.003411,0.589451,0.003040
10,week7,max,DecisionTreeClassifier,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.506883,0.013233,0.468966,0.008135,0.487152,0.009650,0.572187,0.009372,0.579885,0.010240
11,week7,max,GaussianNB,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.522672,0.004907,0.764902,0.006819,0.620987,0.004584,0.687756,0.002843,0.602779,0.005947
12,week7,max,RandomForestClassifier,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.514724,0.009315,0.516285,0.010116,0.515419,0.006254,0.608429,0.011528,0.587018,0.007593
13,week7,max,SVC,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.619967,0.007353,0.448247,0.010318,0.520263,0.008486,0.670544,0.004056,0.648379,0.004690
14,week7,max,KNeighborsClassifier,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.534174,0.009679,0.483452,0.010618,0.507494,0.008455,0.618206,0.010914,0.600837,0.007323
15,week7,sum,DecisionTreeClassifier,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.503484,0.002705,0.470809,0.009705,0.486555,0.005396,0.569029,0.002292,0.577345,0.002128
16,week7,sum,GaussianNB,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.521570,0.004371,0.771311,0.006753,0.622307,0.004255,0.688353,0.002799,0.601696,0.005372
17,week7,sum,RandomForestClassifier,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.504647,0.007395,0.511192,0.011279,0.507865,0.008347,0.603541,0.004368,0.578577,0.006359
18,week7,sum,SVC,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.619992,0.007797,0.449301,0.009563,0.520991,0.008304,0.670701,0.003784,0.648566,0.004913
19,week7,sum,KNeighborsClassifier,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.538734,0.009870,0.483011,0.015028,0.509286,0.011351,0.621953,0.009941,0.604123,0.007601
20,week10,max,DecisionTreeClassifier,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.503820,0.009204,0.470141,0.013066,0.486375,0.010898,0.581205,0.007848,0.593118,0.006996
21,week10,max,GaussianNB,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.517794,0.005504,0.766380,0.008088,0.618013,0.005679,0.704312,0.007178,0.611723,0.006602
22,week10,max,RandomForestClassifier,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.510566,0.002053,0.505615,0.012588,0.508003,0.005863,0.621841,0.001939,0.598719,0.001550
23,week10,max,SVC,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.637448,0.010902,0.433265,0.003662,0.515868,0.005492,0.682337,0.006418,0.666692,0.005204
24,week10,max,KNeighborsClassifier,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.545375,0.006153,0.481562,0.009025,0.511460,0.006933,0.639694,0.005146,0.623001,0.004464
25,week10,sum,DecisionTreeClassifier,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.500988,0.006980,0.465556,0.009484,0.482611,0.008041,0.576688,0.005333,0.590932,0.005331
26,week10,sum,GaussianNB,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.516693,0.005510,0.771622,0.008029,0.618923,0.005781,0.704954,0.007003,0.610572,0.006680
27,week10,sum,RandomForestClassifier,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.513952,0.004368,0.505336,0.007511,0.509589,0.005165,0.622707,0.001327,0.601404,0.003536
28,week10,sum,SVC,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.634878,0.012059,0.435043,0.002554,0.516267,0.004940,0.681849,0.006514,0.665849,0.005564
29,week10,sum,KNeighborsClassifier,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.543811,0.003855,0.475758,0.008518,0.507486,0.005699,0.637749,0.004168,0.621581,0.002819

  KNeighborsClassifier: f1=0.5002, recall=0.4752, roc_auc=0.6060, accuracy=0.5867

Evaluating week5/sum with features: ['total_click_until_cutoff_sum_strategy', 'active_days_until_cutoff']
  DecisionTreeClassifier: f1=0.4844, recall=0.4677, roc_auc=0.5640, accuracy=0.5666
  GaussianNB: f1=0.6223, recall=0.7713, roc_auc=0.6735, accuracy=0.5925
  RandomForestClassifier: f1=0.5179, recall=0.5265, roc_auc=0.5917, accuracy=0.5732
  SVC: f1=0.5281, recall=0.4688, roc_auc=0.6588, accuracy=0.6354
  KNeighborsClassifier: f1=0.5059, recall=0.4828, roc_auc=0.6061, accuracy=0.5895

[week7] rows: 26,776
final_result distribution:
final_result
Distinction     3024
Fail            7044
Pass           12361
Withdrawn       4347
Name: count, dtype: int64
target_struggling distribution:
target_struggling
0    15385
1    11391
Name: count, dtype: int64

Evaluating week7/max with features: ['total_click_until_cutoff_max_strategy', 'active_days_until_cutoff']
  DecisionTreeClassifier: f1=0.4872, recall=0.4690, roc_auc=0.5722, accuracy=0.5799
  GaussianNB: f1=0.6210, recall=0.7649, roc_auc=0.6878, accuracy=0.6028
  RandomForestClassifier: f1=0.5154, recall=0.5163, roc_auc=0.6084, accuracy=0.5870
  SVC: f1=0.5203, recall=0.4482, roc_auc=0.6705, accuracy=0.6484
  KNeighborsClassifier: f1=0.5075, recall=0.4835, roc_auc=0.6182, accuracy=0.6008

Evaluating week7/sum with features: ['total_click_until_cutoff_sum_strategy', 'active_days_until_cutoff']
  DecisionTreeClassifier: f1=0.4866, recall=0.4708, roc_auc=0.5690, accuracy=0.5773
  GaussianNB: f1=0.6223, recall=0.7713, roc_auc=0.6884, accuracy=0.6017
  RandomForestClassifier: f1=0.5079, recall=0.5112, roc_auc=0.6035, accuracy=0.5786
  SVC: f1=0.5210, recall=0.4493, roc_auc=0.6707, accuracy=0.6486
  KNeighborsClassifier: f1=0.5093, recall=0.4830, roc_auc=0.6220, accuracy=0.6041

[week10] rows: 26,069
final_result distribution:
final_result
Distinction     3024
Fail            7044
Pass           12361
Withdrawn       3640
Name: count, dtype: int64
target_struggling distribution:
target_struggling
0    15385
1    10684
Name: count, dtype: int64

Evaluating week10/max with features: ['total_click_until_cutoff_max_strategy', 'active_days_until_cutoff']
  DecisionTreeClassifier: f1=0.4864, recall=0.4701, roc_auc=0.5812, accuracy=0.5931
  GaussianNB: f1=0.6180, recall=0.7664, roc_auc=0.7043, accuracy=0.6117
  RandomForestClassifier: f1=0.5080, recall=0.5056, roc_auc=0.6218, accuracy=0.5987
  SVC: f1=0.5159, recall=0.4333, roc_auc=0.6823, accuracy=0.6667
  KNeighborsClassifier: f1=0.5115, recall=0.4816, roc_auc=0.6397, accuracy=0.6230

Evaluating week10/sum with features: ['total_click_until_cutoff_sum_strategy', 'active_days_until_cutoff']
  DecisionTreeClassifier: f1=0.4826, recall=0.4656, roc_auc=0.5767, accuracy=0.5909
  GaussianNB: f1=0.6189, recall=0.7716, roc_auc=0.7050, accuracy=0.6106
  RandomForestClassifier: f1=0.5096, recall=0.5053, roc_auc=0.6227, accuracy=0.6014
  SVC: f1=0.5163, recall=0.4350, roc_auc=0.6818, accuracy=0.6658
  KNeighborsClassifier: f1=0.5075, recall=0.4758, roc_auc=0.6377, accuracy=0.6216

,cutoff,strategy,model,n_rows,positive_class,features,precision_mean,precision_std,recall_mean,recall_std,f1_mean,f1_std,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,week5,max,DecisionTreeClassifier,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.506331,0.005455,0.471794,0.009029,0.488409,0.005643,0.568405,0.005441,0.569814,0.004464
1,week5,max,GaussianNB,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.523263,0.004299,0.763301,0.005482,0.620877,0.003672,0.672957,0.003109,0.594223,0.005226
2,week5,max,RandomForestClassifier,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.508454,0.005570,0.525002,0.003861,0.516581,0.003741,0.595677,0.006471,0.572273,0.005008
3,week5,max,SVC,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.604104,0.005402,0.464120,0.009698,0.524876,0.005905,0.658852,0.003176,0.634305,0.002962
4,week5,max,KNeighborsClassifier,27244,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.528010,0.010540,0.475166,0.010483,0.500191,0.010403,0.606032,0.007638,0.586661,0.008317
5,week5,sum,DecisionTreeClassifier,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.502443,0.008023,0.467663,0.008370,0.484381,0.006201,0.564044,0.008037,0.566620,0.006482
6,week5,sum,GaussianNB,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.521574,0.004439,0.771312,0.006357,0.622311,0.004280,0.673505,0.003113,0.592461,0.005516
7,week5,sum,RandomForestClassifier,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.509510,0.006247,0.526520,0.004350,0.517860,0.004480,0.591673,0.005117,0.573227,0.005525
8,week5,sum,SVC,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.604740,0.004937,0.468842,0.009892,0.528124,0.005821,0.658785,0.002916,0.635369,0.002643
9,week5,sum,KNeighborsClassifier,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.531268,0.003876,0.482840,0.006847,0.505882,0.004856,0.606051,0.003411,0.589451,0.003040
10,week7,max,DecisionTreeClassifier,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.506883,0.013233,0.468966,0.008135,0.487152,0.009650,0.572187,0.009372,0.579885,0.010240
11,week7,max,GaussianNB,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.522672,0.004907,0.764902,0.006819,0.620987,0.004584,0.687756,0.002843,0.602779,0.005947
12,week7,max,RandomForestClassifier,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.514724,0.009315,0.516285,0.010116,0.515419,0.006254,0.608428,0.011528,0.587018,0.007593
13,week7,max,SVC,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.619967,0.007353,0.448247,0.010318,0.520263,0.008486,0.670544,0.004056,0.648379,0.004690
14,week7,max,KNeighborsClassifier,26776,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.534174,0.009679,0.483452,0.010618,0.507494,0.008455,0.618206,0.010914,0.600837,0.007323
15,week7,sum,DecisionTreeClassifier,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.503484,0.002705,0.470809,0.009705,0.486555,0.005396,0.569029,0.002292,0.577345,0.002128
16,week7,sum,GaussianNB,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.521570,0.004371,0.771311,0.006753,0.622307,0.004255,0.688353,0.002799,0.601696,0.005372
17,week7,sum,RandomForestClassifier,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.504647,0.007395,0.511192,0.011279,0.507865,0.008347,0.603542,0.004369,0.578577,0.006359
18,week7,sum,SVC,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.619992,0.007797,0.449301,0.009563,0.520991,0.008304,0.670701,0.003784,0.648566,0.004913
19,week7,sum,KNeighborsClassifier,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.538734,0.009870,0.483011,0.015028,0.509286,0.011351,0.621953,0.009941,0.604123,0.007601
20,week10,max,DecisionTreeClassifier,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.503820,0.009204,0.470141,0.013066,0.486375,0.010898,0.581205,0.007848,0.593118,0.006996
21,week10,max,GaussianNB,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.517794,0.005504,0.766380,0.008088,0.618013,0.005679,0.704312,0.007178,0.611723,0.006602
22,week10,max,RandomForestClassifier,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.510566,0.002053,0.505615,0.012588,0.508003,0.005863,0.621840,0.001940,0.598719,0.001550
23,week10,max,SVC,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.637448,0.010902,0.433265,0.003662,0.515868,0.005492,0.682337,0.006418,0.666692,0.005204
24,week10,max,KNeighborsClassifier,26069,struggling,"total_click_until_cutoff_max_strategy,active_d...",0.545375,0.006153,0.481562,0.009025,0.511460,0.006933,0.639694,0.005146,0.623001,0.004464
25,week10,sum,DecisionTreeClassifier,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.500988,0.006980,0.465556,0.009484,0.482611,0.008041,0.576688,0.005333,0.590932,0.005331
26,week10,sum,GaussianNB,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.516693,0.005510,0.771622,0.008029,0.618923,0.005781,0.704954,0.007003,0.610572,0.006680
27,week10,sum,RandomForestClassifier,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.513952,0.004368,0.505336,0.007511,0.509589,0.005165,0.622707,0.001328,0.601404,0.003536
28,week10,sum,SVC,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.634878,0.012059,0.435043,0.002554,0.516267,0.004940,0.681849,0.006514,0.665849,0.005564
29,week10,sum,KNeighborsClassifier,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.543811,0.003855,0.475758,0.008518,0.507486,0.005699,0.637749,0.004168,0.621581,0.002819

## 6. 결과 저장

전체 결과는 `paper_replication_baseline_results.csv`에 저장한다. cutoff별 대표 결과는 struggling 클래스 기준 `f1_mean`을 우선 기준으로 선택하고, 동률일 경우 `roc_auc_mean`, `recall_mean`, `accuracy_mean` 순서로 정렬해 `paper_replication_baseline_best_by_cutoff.csv`에 저장한다.

In [8]:
results_path = REPORT_TABLE_DIR / "paper_replication_baseline_results.csv"
best_path = REPORT_TABLE_DIR / "paper_replication_baseline_best_by_cutoff.csv"

sort_columns = ["cutoff", "f1_mean", "roc_auc_mean", "recall_mean", "accuracy_mean"]
best_by_cutoff = (
    results.sort_values(sort_columns, ascending=[True, False, False, False, False])
    .groupby("cutoff", as_index=False)
    .head(1)
    .sort_values("cutoff")
    .reset_index(drop=True)
)

results.to_csv(results_path, index=False, encoding="utf-8")
best_by_cutoff.to_csv(best_path, index=False, encoding="utf-8")

print(f"Saved full results: {results_path}")
print(f"Saved best by cutoff: {best_path}")

best_by_cutoff

Saved full results: C:\Users\osca0\Dev\studyDataMining\teamproject\reports\tables\paper_replication_baseline_results.csv
Saved best by cutoff: C:\Users\osca0\Dev\studyDataMining\teamproject\reports\tables\paper_replication_baseline_best_by_cutoff.csv

,cutoff,strategy,model,n_rows,positive_class,features,precision_mean,precision_std,recall_mean,recall_std,f1_mean,f1_std,roc_auc_mean,roc_auc_std,accuracy_mean,accuracy_std
0,week10,sum,GaussianNB,26069,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.516693,0.005510,0.771622,0.008029,0.618923,0.005781,0.704954,0.007003,0.610572,0.006680
1,week5,sum,GaussianNB,27244,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.521574,0.004439,0.771312,0.006357,0.622311,0.004280,0.673505,0.003113,0.592461,0.005516
2,week7,sum,GaussianNB,26776,struggling,"total_click_until_cutoff_sum_strategy,active_d...",0.521570,0.004371,0.771311,0.006753,0.622307,0.004255,0.688353,0.002799,0.601696,0.005372

## 7. 해석 시 주의사항

이 노트북은 엄격한 두-feature 논문 재현형 베이스라인이다. 성능이 낮거나 특정 모델이 불안정하더라도 이는 더 많은 특징을 추가하기 전의 기준선으로 해석해야 한다.

특히 이 실험은 인구통계, assessment, module/presentation, activity_type-specific click feature를 의도적으로 제외했기 때문에 최종 모델 후보가 아니다. VLE 중복 처리 문제의 영향은 max strategy와 sum strategy의 결과 차이로 별도 확인한다.